import { Speaker, AgendaItem, FAQItem, Partner, PollQuestion } from './types';

export const SPEAKERS: Speaker[] = [
  {
    id: 'ceo-business-china',
    name: 'Kwek Poh Heok',
    nameZh: '郭璞玉',
    role: 'Chief Executive Officer',
    roleZh: '总经理',
    company: 'Business China',
    companyZh: '通商中国',
    bio: 'Kwek Poh Heok is the Chief Executive Officer of Business China, dedicated to fostering closer ties between Singapore and China through various cultural and economic exchange initiatives.',
    bioZh: '郭璞玉是通商中国总经理，致力于通过各项文化与经济交流倡议促进新中两国之间更紧密的联系。',
    avatar: 'KPH',
    category: 'Speaker',
    categoryZh: '发言嘉宾'
  },
  {
    id: 'guest-of-honour',
    name: 'Goh Pei Ming',
    nameZh: '吴佩明',
    role: 'Minister of State, Ministry of Home Affairs & Ministry of Social and Family Development',
    roleZh: '内政部兼社会及家庭发展部政务部长',
    company: 'Government of Singapore',
    companyZh: '新加坡政府',
    bio: 'Goh Pei Ming is the Minister of State for the Ministry of Home Affairs & Ministry of Social and Family Development, championing youth empowerment and social development initiatives in Singapore.',
    bioZh: '吴佩明是新加坡内政部兼社会及家庭发展部政务部长，积极倡导新加坡的青年赋能与社会发展项目。',
    avatar: 'GPM',
    category: 'Guest of Honour',
    categoryZh: '主礼嘉宾'
  },
  {
    id: 'alvin-zou',
    name: 'Alvin Zou',
    nameZh: '邹先生',
    role: 'Vice President, Asia Pacific Business Group',
    roleZh: '亚太业务事业群副总裁',
    company: 'SenseTime Asia',
    companyZh: '商汤科技亚太区',
    bio: 'Alvin Zou is the Vice President of the Asia Pacific Business Group at SenseTime Asia, leading artificial intelligence expansion and industrial solution delivery across the region.',
    bioZh: 'Alvin Zou 是商汤科技亚太业务事业群副总裁，领导该区域人工智能业务扩张与产业解决方案的落地。',
    avatar: 'AZ',
    category: 'Panelist',
    categoryZh: '专题讨论嘉宾'
  },
  {
    id: 'dr-lee-yi-chieh',
    name: 'Dr Lee Yi-Chieh',
    nameZh: '李毅杰 博士',
    role: 'Assistant Professor, Department of Computer Science',
    roleZh: '计算机系助理教授',
    company: 'National University of Singapore (NUS)',
    companyZh: '新加坡国立大学',
    bio: 'Dr. Lee Yi-Chieh is an Assistant Professor in the Department of Computer Science at the National University of Singapore (NUS), researching human-robot interaction and emotional AI systems.',
    bioZh: '李毅杰博士是新加坡国立大学（NUS）计算机系助理教授，专注于人机交互与情感人工智能系统的研究。',
    avatar: 'LYC',
    category: 'Panelist',
    categoryZh: '专题讨论嘉宾'
  },
  {
    id: 'fred-yang',
    name: 'Fred Yang',
    nameZh: '杨先生',
    role: 'Founder',
    roleZh: '创始人',
    company: 'UniX AI',
    companyZh: 'UniX AI',
    bio: 'Fred Yang is the Founder of UniX AI, a pioneering robotics startup building advanced embodied intelligence and humanoid robots for general industrial applications.',
    bioZh: 'Fred Yang 是 UniX AI 创始人，该先锋机器人初创企业致力于为通用工业应用构建先进的具身智能与人形机器人。',
    avatar: 'FY',
    category: 'Panelist',
    categoryZh: '专题讨论嘉宾'
  },
  {
    id: 'phoenix-chen',
    name: 'Phoenix Chen',
    nameZh: '陈凤鸣',
    role: 'Co-Founder, CSAIA & CEO',
    roleZh: 'CSAIA 联合创始人兼首席执行官',
    company: 'DistriBrain',
    companyZh: 'DistriBrain',
    bio: 'Phoenix Chen is the Co-Founder of CSAIA and CEO of DistriBrain, orchestrating decentralized compute frameworks and local artificial intelligence ecosystems.',
    bioZh: '陈凤鸣是 CSAIA 联合创始人兼 DistriBrain 首席执行官，致力于构建去中心化算力架构与本土人工智能生态。',
    avatar: 'PC',
    category: 'Moderator',
    categoryZh: '主持人'
  },
  {
    id: 'samuel-tan',
    name: 'Samuel Tan',
    nameZh: '陈先生',
    role: 'Vice President, China and AP, Bosch Digital & CIO',
    roleZh: '博世数字中国及亚太区副总裁兼首席信息官',
    company: 'Bosch China',
    companyZh: '博世中国',
    bio: 'Samuel Tan is the Vice President of China and AP at Bosch Digital and the CIO of Bosch China, steering digital transformation and IoT solutions at scale.',
    bioZh: 'Samuel Tan 是博世数字中国及亚太区副总裁兼博世中国首席信息官，引领大规模数字转型与物联网解决方案。',
    avatar: 'ST',
    category: 'Panelist',
    categoryZh: '专题讨论嘉宾'
  },
  {
    id: 'tan-yew-guan',
    name: 'Tan Yew Guan',
    nameZh: '陈耀源',
    role: 'Shanghai Correspondent',
    roleZh: '常驻上海记者',
    company: 'Channel NewsAsia (CNA)',
    companyZh: '新加坡亚洲新闻台 (CNA)',
    bio: 'Tan Yew Guan is the Shanghai Correspondent for Channel NewsAsia (CNA), reporting on key economic, technological, and social shifts in Greater China.',
    bioZh: '陈耀源是新加坡亚洲新闻台（CNA）常驻上海记者，报道大中华区的重要经济、科技与社会变革。',
    avatar: 'TYG',
    category: 'Moderator',
    categoryZh: '主持人'
  },
  {
    id: 'vincent-ng',
    name: 'Vincent Ng',
    nameZh: '翁清海',
    role: 'Actor, Martial Artist & Founder, Wufang Singapore & President',
    roleZh: '演员、武术家、无防新加坡创始人兼会长',
    company: 'MMAAS',
    companyZh: 'MMAAS',
    bio: 'Vincent Ng is a renowned actor, martial artist, and the Founder of Wufang Singapore. He serves as the President of MMAAS, blending traditional arts with branding.',
    bioZh: '翁清海是著名演员、武术家，也是无防新加坡（Wufang Singapore）创始人。他担任 MMAAS 会长，将传统艺术与品牌塑造有机结合。',
    avatar: 'VN',
    category: 'Panelist',
    categoryZh: '专题讨论嘉宾'
  },
  {
    id: 'shayna-ng',
    name: 'Shayna Ng',
    nameZh: '黄雅婷',
    role: 'National Athlete & Chairman',
    roleZh: '国家运动员兼主席',
    company: 'Singapore National Olympic Council Athlete\'s Commission',
    companyZh: '新加坡国家奥林匹克委员会运动员委员会',
    bio: 'Shayna Ng is a decorated Singaporean National Athlete and the Chairman of the Singapore National Olympic Council Athletes\' Commission, promoting sports excellence.',
    bioZh: '黄雅婷是新加坡国家运动员，现任新加坡国家奥林匹克委员会运动员委员会主席，致力于推广体育卓越精神。',
    avatar: 'SN',
    category: 'Panelist',
    categoryZh: '专题讨论嘉宾'
  },
  {
    id: 'dr-lee-chih-horng',
    name: 'Dr Lee Chih Horng',
    nameZh: '李气虹 博士',
    role: 'Associate China News Editor, Lianhe Zaobao',
    roleZh: '《联合早报》中国新闻副主任',
    company: 'SPH Media',
    companyZh: '新报业媒体',
    bio: 'Dr. Lee Chih Horng is the Associate China News Editor at Lianhe Zaobao, SPH Media, providing deep analysis and coverage of China\'s structural and social developments.',
    bioZh: '李气虹博士是新报业媒体《联合早报》中国新闻副主任，对中国的发展动态有着深入的分析与报道。',
    avatar: 'LCH',
    category: 'Moderator',
    categoryZh: '主持人'
  },
  {
    id: 'tony-rampton',
    name: 'Tony Rampton',
    nameZh: '托尼·兰普顿',
    role: 'Former Olympian & Principal, Early Years and Primary School',
    roleZh: '前奥运选手兼幼小部校长',
    company: 'Shanghai Singapore International School',
    companyZh: '上海新加坡外籍人员子女学校',
    bio: 'Tony Rampton is a former Olympian and the Principal of the Early Years and Primary School at Shanghai Singapore International School, championing sports leadership in education.',
    bioZh: '托尼·兰普顿是前奥运选手，现任上海新加坡外籍人员子女学校幼小部校长，在教育中倡导体育领导力。',
    avatar: 'TR',
    category: 'Panelist',
    categoryZh: '专题讨论嘉宾'
  },
  {
    id: 'lim-aik-leong',
    name: 'Lim Aik Leong',
    nameZh: '林益良',
    role: 'Vice President, Sports Performance',
    roleZh: '专业运动副总裁',
    company: 'Adidas Greater China',
    companyZh: '阿迪达斯大中华区',
    bio: 'Lim Aik Leong is the Vice President of Sports Performance at Adidas Greater China, driving product strategy and brand resonance across the Chinese market.',
    bioZh: '林益良是阿迪达斯大中华区专业运动副总裁，负责推动中国市场的产品战略与品牌共鸣。',
    avatar: 'LAL',
    category: 'Panelist',
    categoryZh: '专题讨论嘉宾'
  },
  {
    id: 'jenny-chan',
    name: 'Jenny Chan',
    nameZh: '陈女士',
    role: 'Editor',
    roleZh: '编辑',
    company: 'WARC China, LIONS Intelligence',
    companyZh: 'WARC 中国兼 LIONS Intelligence',
    bio: 'Jenny Chan is the Editor for WARC China and LIONS Intelligence, decoding consumer behavior, branding trends, and creative marketing strategies in China.',
    bioZh: 'Jenny Chan 是 WARC 中国兼 LIONS Intelligence 编辑，深谙中国市场的消费者行为、品牌趋势与创意营销策略。',
    avatar: 'JC',
    category: 'Moderator',
    categoryZh: '主持人'
  },
  {
    id: 'simon-yan',
    name: 'Simon Yan',
    nameZh: '严先生',
    role: 'Director, E-Commerce Operations',
    roleZh: '电商运营总监',
    company: 'TikTok Shop',
    companyZh: 'TikTok Shop',
    bio: 'Simon Yan is the Director of E-Commerce Operations at TikTok Shop, leading merchant growth and marketplace scaling strategies in Southeast Asia.',
    bioZh: 'Simon Yan 是 TikTok Shop 电商运营总监，领导东南亚商户成长与电商平台规模化扩张战略。',
    avatar: 'SY',
    category: 'Panelist',
    categoryZh: '专题讨论嘉宾'
  },
  {
    id: 'damon-lye',
    name: 'Damon Lye (Yihao)',
    nameZh: '赖毅豪',
    role: 'Founder & ex-CEO Ergotune & Founder',
    roleZh: 'Ergotune 联合创始人兼前首席执行官、Second Surface 创始人',
    company: 'Second Surface',
    companyZh: 'Second Surface',
    bio: 'Damon Lye is the Co-Founder and former CEO of Ergotune, and Founder of Second Surface, specializing in ergonomic product innovations and cross-border DTC branding.',
    bioZh: '赖毅豪是 Ergotune 联合创始人兼前首席执行官，以及 Second Surface 创始人，专注于人体工学产品创新与跨国直接面向消费者（DTC）的品牌出海。',
    avatar: 'DL',
    category: 'Panelist',
    categoryZh: '专题讨论嘉宾'
  },
  {
    id: 'phuong-ha',
    name: 'Phuong Ha',
    nameZh: '阮芳荷',
    role: 'Co-Founder & CEO',
    roleZh: '联合创始人兼首席执行官',
    company: 'The Metub Company',
    companyZh: 'The Metub Company',
    bio: 'Phuong Ha is the Co-Founder and CEO of The Metub Company, a leading digital media network and talent incubator in Southeast Asia.',
    bioZh: '阮芳荷是 The Metub Company 联合创始人兼首席执行官，该公司是东南亚领先的数字媒体 network 与达人孵化机构。',
    avatar: 'PH',
    category: 'Panelist',
    categoryZh: '专题讨论嘉宾'
  },
  {
    id: 'li-jianggan',
    name: 'Li Jianggan',
    nameZh: '李江干',
    role: 'Founder & CEO',
    roleZh: '创始人兼首席执行官',
    company: 'Momentum Works',
    companyZh: '墨腾创投',
    bio: 'Li Jianggan is the Founder and CEO of Momentum Works, a Singapore-headquartered venture builder and market insights firm focusing on emerging tech ecosystems.',
    bioZh: '李江干是墨腾创投（Momentum Works）创始人兼首席执行官，公司总部位于新加坡，专注于新兴科技生态圈的创业孵化与市场洞察。',
    avatar: 'LJG',
    category: 'Moderator',
    categoryZh: '主持人'
  },
  {
    id: 'toh-jun-jie',
    name: 'Toh Jun Jie',
    nameZh: '卓俊杰',
    role: 'Co-Chairperson',
    roleZh: '联合主席',
    company: 'BCYF Organising Committee',
    companyZh: '通商中国青年论坛组委会',
    bio: 'Toh Jun Jie is the Co-Chairperson of the Business China Youth Forum Organising Committee, leading youth initiatives to connect Singapore-China ecosystems.',
    bioZh: '卓俊杰是通商中国青年论坛组委会联合主席，致力于领导推动连结新中生态圈的青年项目。',
    avatar: 'TJJ',
    category: 'Speaker',
    categoryZh: '发言嘉宾'
  },
  {
    id: 'shen-yihan',
    name: 'Shen Yihan',
    nameZh: '沈一涵',
    role: 'Co-Chairperson',
    roleZh: '联合主席',
    company: 'BCYF Organising Committee',
    companyZh: '通商中国青年论坛组委会',
    bio: 'Shen Yihan is the Co-Chairperson of the Business China Youth Forum Organising Committee, coordinating cross-cultural student projects and youth forums.',
    bioZh: '沈一涵是通商中国青年论坛组委会联合主席，统筹跨文化学生交流与青年论坛项目。',
    avatar: 'SYH',
    category: 'Speaker',
    categoryZh: '发言嘉宾'
  }
];

export const AGENDA: AgendaItem[] = [
  {
    id: 'agenda-1',
    startTime: '11:00',
    endTime: '12:00',
    title: 'Registration + Fringe Activities',
    titleZh: '贵宾签到与周边体验活动',
    description: 'Welcome coffee, verification of tickets, and interactive networking with bicultural galleries and passport challenge booths.',
    descriptionZh: '签到入场、门票核对，以及在前厅展开的“青春护照”和“成果展廊”特色打卡互动。',
    type: 'networking',
    speakers: [],
    location: 'Fringe Activities Area, Sands Expo Level 4',
    locationZh: '濱海灣金沙会展中心4楼前厅'
  },
  {
    id: 'agenda-2',
    startTime: '11:30',
    endTime: '11:50',
    title: 'Closed Door Networking Session',
    titleZh: '闭门交流会议 (定向受邀)',
    description: 'Special networking for selected delegates, student leaders, and VIP corporate hosts.',
    descriptionZh: '面向特邀青年领袖、校友代表与重量级行业导师的专属闭门对接会。',
    type: 'networking',
    speakers: [],
    location: 'Closed Door Lounge, Level 4',
    locationZh: '4楼专属闭门洽谈区'
  },
  {
    id: 'agenda-3',
    startTime: '11:50',
    endTime: '12:00',
    title: 'Guests to be Seated & Gallery Walk',
    titleZh: '代表入座与展区巡礼',
    description: 'Call to order for delegates to take seats inside the Orchid Ballroom. Final interactive walks at the fringe foyer.',
    descriptionZh: '参会代表进入大宴会厅就座。前厅展区巡礼展示收尾。',
    type: 'networking',
    speakers: [],
    location: 'Orchid Ballroom, Level 4',
    locationZh: '大兰花宴会厅，4楼'
  },
  {
    id: 'agenda-4',
    startTime: '12:00',
    endTime: '12:05',
    title: 'Opening of Forum',
    titleZh: '论坛正式开幕',
    description: 'Official commencement of the Business China Youth Forum 2026.',
    descriptionZh: '通商中国青年论坛 2026 大会正式拉开序幕。',
    type: 'ceremony',
    speakers: [],
    location: 'Orchid Ballroom, Level 4',
    locationZh: '大兰花宴会厅，4楼'
  },
  {
    id: 'agenda-5',
    startTime: '12:05',
    endTime: '12:10',
    title: 'Opening Remarks',
    titleZh: '主办机构开幕致辞',
    description: 'Welcome address outlining the vision for this year\'s forum.',
    descriptionZh: '主办机构发表欢迎致辞，阐述本届论坛的核心愿景。',
    type: 'ceremony',
    speakers: ['ceo-business-china'],
    location: 'Orchid Ballroom, Level 4',
    locationZh: '大兰花宴会厅，4楼'
  },
  {
    id: 'agenda-6',
    startTime: '12:10',
    endTime: '12:20',
    title: 'Address by Guest-of-Honour',
    titleZh: '主礼嘉宾开幕演讲',
    description: 'Keynote opening address by Goh Pei Ming, Minister of State.',
    descriptionZh: '主礼嘉宾新加坡政务部长吴佩明发表重要开幕讲话。',
    type: 'keynote',
    speakers: ['guest-of-honour'],
    location: 'Orchid Ballroom, Level 4',
    locationZh: '大兰花宴会厅，4楼'
  },
  {
    id: 'agenda-7',
    startTime: '12:20',
    endTime: '12:35',
    title: 'MOU Launching Ceremony',
    titleZh: '谅解备忘录（MOU）战略签署仪式',
    description: 'Collaboration launch with local polytechnics on developing brand-new China-Ready Programmes.',
    descriptionZh: '与新加坡各理工学院联合启动全新“中国就绪项目”（China-Ready Programmes）的签约合作。',
    type: 'ceremony',
    speakers: ['guest-of-honour'],
    location: 'Orchid Ballroom, Level 4',
    locationZh: '大兰花宴会厅，4楼'
  },
  {
    id: 'agenda-8',
    startTime: '12:35',
    endTime: '12:45',
    title: 'Business China PolyVenture 2025 Best Video Award Presentation',
    titleZh: '通商中国 PolyVenture 2025 最佳视频奖颁奖典礼',
    description: 'Celebrating high-caliber youth creations on cross-border startup ecosystems and cultural discovery.',
    descriptionZh: '为在跨境创业生态和文化探索中做出卓越贡献的青年优秀视频团队颁发最高奖项。',
    type: 'ceremony',
    speakers: [],
    location: 'Orchid Ballroom, Level 4',
    locationZh: '大兰花宴会厅，4楼'
  },
  {
    id: 'agenda-9',
    startTime: '12:45',
    endTime: '14:00',
    title: 'Panel 1: The Rise of AI Companions and Humanoid Robots: Exploring the Emerging Industries Trends',
    titleZh: '专题讨论一：AI陪伴与人形机器人的崛起：探索新兴产业前沿趋势',
    description: 'Delving into how artificial intelligence, emotional companion models, and humanoid embodied hardware are transforming the technological landscape and cross-border partnership potentials.',
    descriptionZh: '深入剖析情感AI陪伴大模型、具身智能硬件与人形机器人的颠覆性突破，及其对新中跨国科技协作和产业链融合的深远影响。',
    type: 'panel',
    speakers: ['alvin-zou', 'dr-lee-yi-chieh', 'fred-yang', 'phoenix-chen', 'samuel-tan', 'tan-yew-guan'],
    location: 'Orchid Ballroom & Shanghai Satellite, Level 4',
    locationZh: '大兰花宴会厅与上海分会场，4楼'
  },
  {
    id: 'agenda-10',
    startTime: '14:00',
    endTime: '14:05',
    title: 'Lucky Moments',
    titleZh: '幸运时刻抽奖环节',
    description: 'Exciting mid-day surprise prizes for interactive attendees.',
    descriptionZh: '现场抽取首批精美好礼，回馈积极参与互动的参会代表。',
    type: 'ceremony',
    speakers: [],
    location: 'Orchid Ballroom, Level 4',
    locationZh: '大兰花宴会厅，4楼'
  },
  {
    id: 'agenda-11',
    startTime: '14:05',
    endTime: '14:30',
    title: 'Tea Break & Gallery Tour',
    titleZh: '下午茶叙与展廊巡游',
    description: 'Refreshments served at the foyer alongside interactive networking.',
    descriptionZh: '前厅供应中西精美茶点，参会代表可在此进行社交交流及展台互动。',
    type: 'networking',
    speakers: [],
    location: 'Fringe Foyer, Level 4',
    locationZh: '4楼前厅体验区'
  },
  {
    id: 'agenda-12',
    startTime: '14:30',
    endTime: '14:45',
    title: 'Business China Summer School Scholarship Award Presentation',
    titleZh: '通商中国暑期学校奖学金颁奖仪式',
    description: 'Commending student achievements in bicultural immersive learning across major Chinese tech and commerce centers.',
    descriptionZh: '表彰在华顶尖科技与商业中心完成双语沉浸式学习的优秀青年学子。',
    type: 'ceremony',
    speakers: [],
    location: 'Orchid Ballroom, Level 4',
    locationZh: '大兰花宴会厅，4楼'
  },
  {
    id: 'agenda-13',
    startTime: '14:45',
    endTime: '16:00',
    title: 'Panel 2: Beyond the Arena: Sports, Branding and Identity',
    titleZh: '专题讨论二：超越竞技场：体育、品牌塑造与身份认同',
    description: 'Exploring how sports, brand strategy, global licensing, and athlete identity shape cultural synergy and commercial opportunities between Southeast Asia and China.',
    descriptionZh: '探讨体育精神、国潮品牌出海、全球商业授权及运动员个人品牌，如何在新中及东南亚市场交织出全新的文化共鸣与商业蓝海。',
    type: 'panel',
    speakers: ['vincent-ng', 'shayna-ng', 'dr-lee-chih-horng', 'tony-rampton', 'lim-aik-leong', 'jenny-chan'],
    location: 'Orchid Ballroom & Shanghai Satellite, Level 4',
    locationZh: '大兰花宴会厅与上海分会场，4楼'
  },
  {
    id: 'agenda-14',
    startTime: '16:00',
    endTime: '16:05',
    title: 'Lucky Moments',
    titleZh: '幸运时刻抽奖环节',
    description: 'Second round of surprise drawings for active participants.',
    descriptionZh: '现场第二轮幸运大抽奖，送出精美礼包。',
    type: 'ceremony',
    speakers: [],
    location: 'Orchid Ballroom, Level 4',
    locationZh: '大兰花宴会厅，4楼'
  },
  {
    id: 'agenda-15',
    startTime: '16:05',
    endTime: '17:20',
    title: 'Panel 3: Connecting the World and Future: The Digital Era of Young Entrepreneurs',
    titleZh: '专题讨论三：联结世界与未来：青年创业者的数字化时代',
    description: 'Discussing digital platforms, social commerce, global tech scaling, and entrepreneurship launchpads bridging the Chinese market and ASEAN.',
    descriptionZh: '聚焦社交电商、智能运营、全球化扩张路径，以及青年创业者如何以新加坡和中国为双向跳板拓展全球数字版图。',
    type: 'panel',
    speakers: ['simon-yan', 'damon-lye', 'phuong-ha', 'li-jianggan'],
    location: 'Orchid Ballroom, Level 4',
    locationZh: '大兰花宴会厅，4楼'
  },
  {
    id: 'agenda-16',
    startTime: '17:20',
    endTime: '17:25',
    title: 'Lucky Moments',
    titleZh: '幸运时刻抽奖环节',
    description: 'Final mini draw before the closing ceremony.',
    descriptionZh: '闭幕前最后一轮惊喜小抽奖。',
    type: 'ceremony',
    speakers: [],
    location: 'Orchid Ballroom, Level 4',
    locationZh: '大兰花宴会厅，4楼'
  },
  {
    id: 'agenda-17',
    startTime: '17:25',
    endTime: '17:35',
    title: 'Closing Address by BCYF Organising Committee Co-Chairpersons',
    titleZh: '青年论坛组委会联合主席闭幕演讲',
    description: 'Closing address summarizing findings, recommendations, and bicultural leadership commitments.',
    descriptionZh: '组委会联合主席卓俊杰与沈一涵发表闭幕致辞，总结大会思辨成果与双文化领袖誓言。',
    type: 'keynote',
    speakers: ['toh-jun-jie', 'shen-yihan'],
    location: 'Orchid Ballroom, Level 4',
    locationZh: '大兰花宴会厅，4楼'
  },
  {
    id: 'agenda-18',
    startTime: '17:35',
    endTime: '17:45',
    title: 'Grand Lucky Draw, BCYF Survey, Group Photo',
    titleZh: '终极锦鲤大抽奖、满意度调研与合影留念',
    description: 'The main prize drawing, survey collection, and mass group photography with all delegates.',
    descriptionZh: '揭晓全场终极超级大奖，收集代表调研反馈，并组织全场嘉宾与代表合影留念。',
    type: 'ceremony',
    speakers: [],
    location: 'Orchid Ballroom, Level 4',
    locationZh: '大兰花宴会厅，4楼'
  }
];

export const FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'What is the Business China Youth Forum (BCYF)?',
    questionZh: '什么是通商中国青年论坛 (BCYF)？',
    answer: 'The Business China Youth Forum (BCYF) is a premier signature platform that brings together outstanding bilingual and bicultural youths, professionals, and global leaders. Co-hosted under the Future China Global Forum, it aims to empower young voices, foster entrepreneurial partnerships, and deepen mutual understanding between Singapore and China.',
    answerZh: '通商中国青年论坛（BCYF）是一个汇聚杰出双语双文化青年、专业人士及全球领袖的旗舰平台。作为“慧眼中国全球论坛”的子论坛，它旨在表达青年心声、促进创业合作，并深化新加坡与中国之间的相互理解。',
    category: 'general'
  },
  {
    id: 'faq-2',
    question: 'How do I register for the forum, and is it free?',
    questionZh: '我该如何注册参加论坛？是否免费？',
    answer: 'Registration can be completed via our online portal. There are limited complimentary passes available for current full-time students. Regular admission passes include access to all keynotes, panel discussions, interactive workshops, and the networking luncheon.',
    answerZh: '您可以通过我们的在线门户完成注册。我们为全日制在校学生提供数量有限的免费入场券。普通门票包含所有主旨演讲、专题讨论会、互动工作坊的入场资格，以及双语社交午宴。',
    category: 'registration'
  },
  {
    id: 'faq-3',
    question: 'Where is the event located, and what is the dress code?',
    questionZh: '活动地点在哪里？着装要求是什么？',
    answer: 'The forum will take place at the Sands Expo & Convention Centre, Level 4 Orchid Ballroom, Singapore. The dress code is Business Smart / Business Formal. Traditional cultural attire or corporate smart wear are highly encouraged.',
    answerZh: '本次论坛将在新加坡滨海湾金沙会展中心（Sands Expo & Convention Centre）4楼兰花大宴会厅举行。着装要求为商务休闲（Business Smart）或商务正装（Business Formal）。欢迎穿着传统文化服饰或商务正装。',
    category: 'venue'
  },
  {
    id: 'faq-4',
    question: 'Are sessions conducted in English or Chinese?',
    questionZh: '论坛是英文进行还是中文进行？',
    answer: 'In line with Business China\'s mission, sessions are bilingual. Keynote speeches and panel discussions are conducted in either English or Mandarin, with simultaneous real-time AI translation / subtitle streams visible on main presentation displays.',
    answerZh: '契合通商中国“架设双语双文化桥梁”的使命，所有环节均为双语进行。主旨演讲和专题讨论将以英语或中文进行，并在主屏幕上提供实时的双语AI字幕翻译。',
    category: 'general'
  }
];

export const PARTNERS: Partner[] = [
  {
    id: 'p-1',
    name: 'Business China',
    category: 'Organiser',
    categoryZh: '主办机构',
    logoText: 'Business China',
    url: 'https://www.businesschina.org.sg'
  },
  {
    id: 'p-2',
    name: 'Ministry of Trade and Industry Singapore',
    category: 'Co-organiser',
    categoryZh: '联合主办机构',
    logoText: 'MTI Singapore',
    url: 'https://www.mti.gov.sg'
  },
  {
    id: 'p-3',
    name: 'National Youth Council Singapore',
    category: 'Strategic Partner',
    categoryZh: '战略合作伙伴',
    logoText: 'NYC Singapore',
    url: 'https://www.nyc.gov.sg'
  },
  {
    id: 'p-4',
    name: 'Enterprise Singapore',
    category: 'Supporting Partner',
    categoryZh: '支持机构',
    logoText: 'Enterprise SG',
    url: 'https://www.enterprisesg.gov.sg'
  },
  {
    id: 'p-5',
    name: 'The Business Times',
    category: 'Media Partner',
    categoryZh: '媒体合作伙伴',
    logoText: 'Business Times',
    url: 'https://www.businesstimes.com.sg'
  }
];

export const INITIAL_POLLS: PollQuestion[] = [
  {
    id: 'poll-1',
    question: 'Which sector has the most exciting growth potential for Singapore-China youth entrepreneurship in 2026?',
    questionZh: '2026年，哪个领域对于新中青年创业最具令人振奋的增长潜力？',
    options: [
      { id: 'opt-1', text: 'Smart Green Mobility & Decarbonization', textZh: '智能绿色出行与脱碳科技', votes: 114 },
      { id: 'opt-2', text: 'Cross-Border Supply Chain Innovations', textZh: '跨国供应链与智能物流创新', votes: 85 },
      { id: 'opt-3', text: 'Digital Heritage & Cross-Cultural EdTech', textZh: '数字文化传承与双语教育科技', votes: 56 },
      { id: 'opt-4', text: 'Generative Tech for SME Empowerment', textZh: '赋能中小企业的生成式技术', votes: 72 }
    ]
  }
];

export const TRANSLATIONS = {
  en: {
    navHome: 'Home',
    navAbout: 'About',
    navSchedule: 'Schedule',
    navSpeakers: 'Speakers',
    navInteractive: 'Interactive Hub',
    navFaq: 'FAQ',
    heroSubtitle: 'Business China Youth Forum (BCYF)',
    heroTitleFirst: 'The World in',
    heroTitleHighlight: 'Flux',
    heroTitleLast: 'Youth Navigating in an Age of Uncertainty',
    heroDate: '12th September 2026',
    heroVenue: 'Sands Expo & Convention Centre, Singapore',
    countdownDays: 'Days',
    countdownHours: 'Hours',
    countdownMinutes: 'Minutes',
    countdownSeconds: 'Seconds',
    countdownFinished: 'Event Has Commenced!',
    registerBtn: 'Register Now',
    exploreBtn: 'Explore Experiences',
    statsRegistrants: 'Attendees Registered',
    statsSpeakers: 'Bicultural Speakers',
    statsPanels: 'Key Dialogues',
    statsCountries: 'Partner Economies',
    aboutTitle: 'About the Forum',
    aboutSubtitle: 'Connecting ASEAN and China through Youth Ingenuity',
    aboutDesc1: 'Established under the wings of Business China, the Business China Youth Forum (BCYF) is the definitive platform for future-ready young leaders. Under the parent umbrella of the Future China Global Forum (FCGF), BCYF 2026 prepares bilingual, bicultural Singaporeans and global youth to navigate an increasingly interconnected Asia and the rapidly changing future of work.',
    aboutDesc2: 'This year\'s theme, "The World in Flux: Youth Navigating in an Age of Uncertainty" (变局中的世界：青年在不确定性时代中领航), focuses on equipping youths with the knowledge, networks, and confidence needed to shape their own destiny. Through dynamic discussions on emerging industries, green transition, cross-border opportunities, and real-world technology application, BCYF 2026 empowers youths to proactively innovate rather than merely adapt to change.',
    agendaTitle: 'Programme Agenda',
    agendaSubtitle: 'Plan your day at BCYF 2026. Save items to build your personal bicultural itinerary.',
    agendaFilterAll: 'All Sessions',
    agendaFilterKeynote: 'Keynotes',
    agendaFilterPanel: 'Panels',
    agendaFilterNetworking: 'Social / Luncheon',
    agendaFilterWorkshop: 'Workshops',
    speakersTitle: 'Featured Speakers',
    speakersSubtitle: 'Learn from visionary founders, corporate architects, and high-ranking policymakers.',
    speakersModalBio: 'Biography',
    speakersModalTopic: 'Featured In',
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Everything you need to know about attendance, logistics, and bilingual programming.',
    faqCatAll: 'All Questions',
    faqCatGeneral: 'General Info',
    faqCatReg: 'Registration',
    faqCatVenue: 'Venue & Access',
    partnersTitle: 'Our Prestigious Partners',
    partnersSubtitle: 'Driven by Singapore and China\'s leading national, cultural, and enterprise organisations.',
    pollTitle: 'Live Audience Pulse',
    pollSubtitle: 'Cast your vote and see live sentiment from delegates surrounding global-Asia trends.',
    pollTotalVotes: 'votes cast',
    pollVotedText: 'Thank you for voting! Here is the live audience breakdown.',
    itineraryTitle: 'My Personalized Itinerary',
    itineraryEmpty: 'You haven\'t saved any sessions yet. Click the calendar plus icons in the schedule to build your itinerary!',
    itinerarySaveBtn: 'Export Itinerary (PDF)',
    itineraryRemove: 'Remove',
    registerTitle: 'Secure Your Seat',
    registerFormSubtitle: 'Join over 800 bicultural delegates, founders, and policy analysts at Sands Expo.',
    registerFormName: 'Full Name',
    registerFormEmail: 'Email Address',
    registerFormOrg: 'Organisation / University',
    registerFormDesignation: 'Job Title / Student Major',
    registerFormDiet: 'Dietary Requirements',
    registerFormDietNone: 'No Restrictions',
    registerFormDietVeg: 'Vegetarian / Halal Friendly',
    registerFormDietGluten: 'Gluten Free / Vegan',
    registerFormSubmit: 'Complete Registration',
    registerSuccessTitle: 'Registration Successful!',
    registerSuccessDesc: 'Your delegate ticket has been reserved. A confirmation email with QR code entry pass has been sent to your inbox.',
    registerCloseBtn: 'Back to Site',
    contactUs: 'Contact Us',
    footerRights: 'All rights reserved. Business China (通商中国) is a non-profit organization.',
    footerSlogan: 'Nurturing bilingual and bicultural leadership for a connected world.',
    
    // Updated Opportunities Translations
    expTitle: 'Interactive Experiences',
    expSubtitle: 'Dive into the special interactive zones, co-creation labs, and challenge sessions designed for BCYF 2026.',
    
    expGalleryTitle: 'Gallery Showcase',
    expGalleryDesc: 'Explore curated career pathways, corporate highlights, and cross-border insights in our physical gallery walk.',
    expGallerySpot: 'Company Spotlight',
    expGalleryCareer: 'Career Pathing',
    expGalleryExpl: 'Industry Explainers',
    
    expDebateTitle: 'Youth Debate Stage',
    expDebateDesc: 'Witness bicultural delegates spar on major motions shaping ASEAN-China relations and the future of work.',
    expDebateMotion: 'Today\'s Live Debate Motion',
    expDebateVoteBtn: 'Which side are you on?',
    expDebateSideA: 'Proposers: Embrace AI-driven leadership',
    expDebateSideB: 'Opposition: Preserve Human-centered values',
    expDebateResult: 'Live Audience Split',
    
    expMouTitle: 'MOU Partnership Arena',
    expMouDesc: 'Bridging national agencies and cross-border tech enterprises in historic cooperation ceremonies.',
    expMouBadge: 'Partnership Announcement',
    expMouCrossPost: 'Social Cross-Post Opportunity',
    
    expPassportTitle: 'Passport Activity Challenge',
    expPassportDesc: 'Pick up your Physical Passport, complete 4 offline booth interactive challenges, and claim your exclusive Business China gift!',
    expPassportStep1: '1. Scan QR Code at main foyer',
    expPassportStep2: '2. Complete 2 Career Spotlights',
    expPassportStep3: '3. Submit vote on live debate motion',
    expPassportStep4: '4. Share a picture on Instagram using #BCYF2026',
    expPassportClaim: 'Claim Gift at Information Counter Level 4'
  },
  zh: {
    navHome: '首页',
    navAbout: '关于论坛',
    navSchedule: '论坛议程',
    navSpeakers: '演讲嘉宾',
    navInteractive: '互动专区',
    navFaq: '常见问题',
    heroSubtitle: '通商中国青年论坛 (BCYF)',
    heroTitleFirst: '变局中的',
    heroTitleHighlight: '世界',
    heroTitleLast: '青年在不确定性时代中领航',
    heroDate: '2026年9月12日',
    heroVenue: '滨海湾金沙会展中心，新加坡',
    countdownDays: '天',
    countdownHours: '时',
    countdownMinutes: '分',
    countdownSeconds: '秒',
    countdownFinished: '大会已盛大开幕！',
    registerBtn: '立即报名参会',
    exploreBtn: '探索特色体验',
    statsRegistrants: '已注册代表',
    statsSpeakers: '双语双文化讲师',
    statsPanels: '核心对话板块',
    statsCountries: '合作经济体',
    aboutTitle: '关于本届论坛',
    aboutSubtitle: '融汇青年智慧，连接东盟与中国未来',
    aboutDesc1: '通商中国青年论坛 (BCYF) 是通商中国旗下专为未来青年领袖打造的旗舰平台。作为“慧眼中国全球论坛 (FCGF)”的青年专属篇章，BCYF 2026 致力于培养兼具双语与双文化能力的新加坡及全球青年，使其能够在日益紧密联系的亚洲以及快速变化的未来职场中破浪前行、开拓无限格局。',
    aboutDesc2: '本届论坛以“变局中的世界：青年在不确定性时代中领航”（The World in Flux: Youth Navigating in an Age of Uncertainty）为主题，旨在为青年人装备前沿知识、拓展国际人脉、树立开拓信心。通过围绕新兴产业、绿色转型、跨国创业和实用创新实践等课题的深度交流，BCYF 2026 赋能青年主动塑造自身未来，在变革大潮中破浪而上。',
    agendaTitle: '论坛精彩议程',
    agendaSubtitle: '规划您的论坛之旅。点击日历图标即可创建您个人的双语/双文化专属日程表。',
    agendaFilterAll: '全部日程',
    agendaFilterKeynote: '主旨演讲',
    agendaFilterPanel: '专题研讨',
    agendaFilterNetworking: '社交午宴',
    agendaFilterWorkshop: '创业工坊',
    speakersTitle: '重磅演讲嘉宾',
    speakersSubtitle: '聆听行业创投领袖、政策倡导者与科技先锋的独到真知灼见。',
    speakersModalBio: '嘉宾简介',
    speakersModalTopic: '主讲环节',
    faqTitle: '热点问题解答',
    faqSubtitle: '为您梳理关于参会申请、金沙会展中心交通指引以及双语同声传译的各项解答。',
    faqCatAll: '全部问题',
    faqCatGeneral: '通用信息',
    faqCatReg: '门票与报名',
    faqCatVenue: '会场与交通',
    partnersTitle: '尊崇合作伙伴',
    partnersSubtitle: '得到了新加坡与中国领先的政府部委、文化机构及顶尖企业的深度鼎力支持。',
    pollTitle: '青年领袖现场民调',
    pollSubtitle: '点击投出您宝贵的一票，实时查看全场青年代表对全球亚洲前沿发展趋势的观点交锋。',
    pollTotalVotes: '人已参与投票',
    pollVotedText: '感谢您的投票！以下为实时民意分布图。',
    itineraryTitle: '我的个性化专属议程',
    itineraryEmpty: '您尚未添加任何议程项目。请在上方日程表中点击“添加”图标，定制您的专属行程！',
    itinerarySaveBtn: '导出我的日程 (PDF)',
    itineraryRemove: '移出',
    registerTitle: '立即抢占席位',
    registerFormSubtitle: '与800余名双语双文化精英、创始人及政策研究员共聚新加坡滨海湾金沙。',
    registerFormName: '中文/英文姓名',
    registerFormEmail: '电子邮件地址',
    registerFormOrg: '就职机构 / 就读高校',
    registerFormDesignation: '职务岗位 / 专业学科',
    registerFormDiet: '膳食习惯',
    registerFormDietNone: '无特殊限制',
    registerFormDietVeg: '素食 / 清真友好',
    registerFormDietGluten: '无麸质 / 严格纯素',
    registerFormSubmit: '提交报名申请',
    registerSuccessTitle: '报名申请提交成功！',
    registerSuccessDesc: '您的参会门票已预订成功。包含入场二维码的电子门票已自动发送至您的邮箱。',
    registerCloseBtn: '返回网站首页',
    contactUs: '联系我们',
    footerRights: '版权所有。通商中国（Business China）为非营利机构。',
    footerSlogan: '架设双语双文化桥梁，培育连接全球的杰出领袖。',
    
    // Updated Opportunities Translations (Chinese)
    expTitle: '特设互动专区',
    expSubtitle: '探索为 BCYF 2026 量身定制的特别互动展区、合作签约平台与趣味青春挑战。',
    
    expGalleryTitle: '职业与成果画廊展示',
    expGalleryDesc: '在实体展区中探索精心筛选的职业路径规划、卓越企业高光及跨国发展机遇。',
    expGallerySpot: '企业高光展台',
    expGalleryCareer: '职业生涯导航',
    expGalleryExpl: '行业深度解析',
    
    expDebateTitle: '青年辩论大舞台',
    expDebateDesc: '见证双语双文化青年代表围绕影响东盟与中国的核心议题展开现场精彩思辨。',
    expDebateMotion: '今日辩论核心辩题',
    expDebateVoteBtn: '您支持哪一方？',
    expDebateSideA: '正方：拥抱人工智能引领的管理模式',
    expDebateSideB: '反方：坚守以人类为本的核心价值观',
    expDebateResult: '现场观众投票比例',
    
    expMouTitle: '备忘录（MOU）战略签署',
    expMouDesc: '见证国家机构与跨国创新企业在高峰会上的历史性合作签约，探索区域生态圈。',
    expMouBadge: '最新战略合作发布',
    expMouCrossPost: '多渠道社交网络联动发布',
    
    expPassportTitle: '“青春护照”探索挑战',
    expPassportDesc: '现场领取实体“青春护照”，完成以下4项打卡任务，即可前往服务台兑换通商中国精美礼品！',
    expPassportStep1: '1. 扫描会场前厅注册二维码',
    expPassportStep2: '2. 完成2个企业高光展台打卡',
    expPassportStep3: '3. 提交今日辩论主题的现场投票',
    expPassportStep4: '4. 在Instagram发布合影并带话题 #BCYF2026',
    expPassportClaim: '金沙会展中心四楼信息服务台兑换精美礼品'
  }
};
